---
name: 'SpamAssassin'
description: 'Verify SpamAssassin rules in your Github Actions.'

inputs:
  directory:
    description: "Source directory name"
    required: false
    default: /
  excluded:
    description: "Files to be excluded from sync"
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://ghcr.io/wagonza/spamassassin-action:v1.0.11'
  env:
    ACTION_DIRECTORY: ${{ inputs.directory }}
    EXCLUDED: ${{ inputs.excluded }}


branding:
  icon: 'book'
  color: 'gray-dark'
