#!/bin/bash
set -e

command_string="spamassassin --lint"

# Copy rules to the right location

rsync --exclude ${EXCLUDED} ${ACTION_DIRECTORY}/*\.cf /etc/spamassassin/

echo "Command: $command_string"
eval "$command_string"
